# Generated by Django 5.2.4 on 2025-07-24 20:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('ano_lancamento', models.PositiveIntegerField()),
                ('duracao', models.PositiveIntegerField(help_text='Duração em minutos')),
                ('assistido', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, help_text='Comentários pessoais sobre o item', null=True)),
                ('atores', models.ManyToManyField(related_name='atuou_em', to='catalog.ator')),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filmes_dirigidos', to='catalog.diretor')),
                ('generos', models.ManyToManyField(related_name='filmes_do_genero', to='catalog.genero')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='catalog.item')),
            ],
            options={
                'unique_together': {('usuario', 'item')},
            },
        ),
    ]
